package claudehook

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// HookFileName is the on-disk name the install writer drops into
// `.claude/hooks/`. Exported so the CLI uninstall path can find it.
const HookFileName = "korva-telemetry.sh"

// hookScript is the body the install writes. Two lines, on purpose:
// the heavy lifting (JSON parsing, auth, POST) lives in the Go binary
// the dev already has on PATH, so a future fix to the protocol is a
// CLI release rather than a script regeneration on every machine.
const hookScript = `#!/usr/bin/env bash
# Korva Claude Code telemetry hook — DO NOT EDIT
# Regenerated by 'korva pkg install'. See ADR 0020 in korva-platform.
exec korva pkg hook --event=user-prompt-submit
`

// EnsureHook writes the Bash script under .claude/hooks/ and merges
// the UserPromptSubmit registration into .claude/settings.json. Both
// operations are idempotent: re-running install never duplicates a
// hook entry, and an existing settings.json untouched by Korva keeps
// its other entries.
//
// Best-effort: any IO failure is returned so the caller can decide
// whether to surface it — `korva pkg install` only warns rather than
// failing the install because a missing hook is a measurement gap,
// not a correctness bug.
func EnsureHook(root string) error {
	return EnsureEventHook(root, HookFileName, hookScript, []string{"UserPromptSubmit"})
}

// EnsureEventHook writes an arbitrary hook script under .claude/hooks/
// and merges its registration into .claude/settings.json for every
// event in events. Shared by the telemetry hook above and the session
// context hooks (internal/sessionhook). Idempotent per (script, event).
func EnsureEventHook(root, fileName, script string, events []string) error {
	hooksDir := filepath.Join(root, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", hooksDir, err)
	}
	hookPath := filepath.Join(hooksDir, fileName)
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write %s: %w", hookPath, err)
	}
	return mergeSettings(root, hookPath, events)
}

// mergeSettings reads .claude/settings.json (if any), merges the
// Korva hook entry under UserPromptSubmit, and writes it back. We
// preserve existing keys exactly; only the array we own is rewritten
// if needed. The format Anthropic accepts:
//
//	{
//	  "hooks": {
//	    "UserPromptSubmit": [
//	      { "matcher": "", "hooks": [ {"type":"command","command":"./.claude/hooks/korva-telemetry.sh"} ] }
//	    ]
//	  }
//	}
func mergeSettings(root, hookPath string, events []string) error {
	settingsPath := filepath.Join(root, ".claude", "settings.json")
	rel, err := filepath.Rel(root, hookPath)
	if err != nil {
		return fmt.Errorf("relpath: %w", err)
	}
	// Claude wants the command runnable from project root; the
	// "./" prefix makes intent explicit even though it isn't strictly
	// required.
	cmdLine := "./" + rel

	var doc map[string]any
	if raw, err := os.ReadFile(settingsPath); err == nil {
		if err := json.Unmarshal(raw, &doc); err != nil {
			// Existing settings.json is corrupt — refuse to clobber.
			// The dev can fix and re-run install; we surface what we
			// found.
			return fmt.Errorf("existing %s is not valid JSON: %w", settingsPath, err)
		}
	}
	if doc == nil {
		doc = map[string]any{}
	}

	hooks, _ := doc["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
	}
	changed := false
	for _, event := range events {
		entries, _ := hooks[event].([]any)
		// Find an existing Korva entry (its inner command points at
		// our script). If present, leave this event alone.
		wired := false
		for _, entry := range entries {
			e, ok := entry.(map[string]any)
			if !ok {
				continue
			}
			inner, _ := e["hooks"].([]any)
			for _, h := range inner {
				hm, ok := h.(map[string]any)
				if !ok {
					continue
				}
				if cmd, _ := hm["command"].(string); cmd == cmdLine {
					wired = true
				}
			}
		}
		if wired {
			continue
		}
		entries = append(entries, map[string]any{
			"matcher": "",
			"hooks": []any{
				map[string]any{
					"type":    "command",
					"command": cmdLine,
				},
			},
		})
		hooks[event] = entries
		changed = true
	}
	if !changed {
		return nil // everything already wired
	}
	doc["hooks"] = hooks

	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal settings: %w", err)
	}
	if err := os.WriteFile(settingsPath, out, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", settingsPath, err)
	}
	return nil
}
