// Package contextfiles renders the .korva/context/ folder: the plain
// markdown files any AI agent reads for portfolio awareness. Layout and
// headers are fixed by the platform's docs/specs/portfolio-context.md.
package contextfiles

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/AlcanDev/korva-cli/internal/api"
)

// Dir is the folder (relative to the project root) the files land in.
const Dir = ".korva/context"

// gitignoreLine is what EnsureGitignore appends: the whole .korva/
// folder stays out of version control — it is generated, per-machine
// state, refreshed by `korva context pull`.
const gitignoreLine = ".korva/"

// Data is everything Pull collected for rendering.
type Data struct {
	ServerURL string
	Project   string
	// Context is nil when the project has no record yet (CI not wired,
	// no brief) — project-brief.md then explains how to wire it.
	Context      *api.ProjectContext
	Portfolio    []api.ProjectContext
	Observations []api.Observation
	GeneratedAt  time.Time
}

// header renders the one-line provenance comment every generated file
// starts with, so a reader (human or agent) knows where it came from
// and how fresh it is.
func header(d Data, sha string) string {
	h := fmt.Sprintf("<!-- generated by korva context pull · %s · %s",
		d.ServerURL, d.GeneratedAt.UTC().Format(time.RFC3339))
	if sha != "" {
		h += " · main@" + shortSHA(sha)
	}
	return h + " -->\n\n"
}

func shortSHA(sha string) string {
	if len(sha) > 12 {
		return sha[:12]
	}
	return sha
}

func relDays(t *time.Time, now time.Time) string {
	if t == nil {
		return "never"
	}
	days := int(now.Sub(*t).Hours() / 24)
	if days <= 0 {
		return "today"
	}
	return fmt.Sprintf("%dd ago", days)
}

// RenderPortfolio produces portfolio.md: one compact block per project.
func RenderPortfolio(d Data) string {
	var b strings.Builder
	b.WriteString(header(d, ""))
	b.WriteString("# Team portfolio\n\n")
	if len(d.Portfolio) == 0 {
		b.WriteString("No projects registered yet.\n")
		return b.String()
	}
	for _, pc := range d.Portfolio {
		fmt.Fprintf(&b, "## %s\n\n", pc.Project)
		if pc.HeadSHA != "" {
			fmt.Fprintf(&b, "- HEAD: `%s@%s` · pushed %s\n", pc.Branch, shortSHA(pc.HeadSHA), relDays(pc.PushedAt, d.GeneratedAt))
		} else {
			b.WriteString("- HEAD: never pushed (CI not wired)\n")
		}
		if pc.RepoURL != "" {
			fmt.Fprintf(&b, "- Repo: %s\n", pc.RepoURL)
		}
		if pc.Stale {
			b.WriteString("- ⚠ Brief is STALE — main moved past the sha it describes\n")
		}
		if pc.BriefMD != "" {
			fmt.Fprintf(&b, "\n%s\n", firstLine(pc.BriefMD))
		}
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// RenderBrief produces project-brief.md for the current project.
func RenderBrief(d Data) string {
	var b strings.Builder
	sha := ""
	if d.Context != nil {
		sha = d.Context.HeadSHA
	}
	b.WriteString(header(d, sha))
	fmt.Fprintf(&b, "# %s\n\n", d.Project)

	if d.Context == nil {
		b.WriteString("This project has no context record yet.\n\n")
		b.WriteString("- Wire CI: mint a push token in the Korva console (Projects → this project → Push tokens) and run `korva context push` on merges to main.\n")
		b.WriteString("- Or ask a Lead to save a brief from the console.\n")
		return b.String()
	}

	pc := d.Context
	if pc.HeadSHA != "" {
		fmt.Fprintf(&b, "- HEAD: `%s@%s` · pushed %s\n", pc.Branch, shortSHA(pc.HeadSHA), relDays(pc.PushedAt, d.GeneratedAt))
	} else {
		b.WriteString("- HEAD: never pushed (CI not wired)\n")
	}
	if pc.RepoURL != "" {
		fmt.Fprintf(&b, "- Repo: %s\n", pc.RepoURL)
	}
	if len(pc.Branches) > 0 {
		names := make([]string, 0, len(pc.Branches))
		for _, br := range pc.Branches {
			names = append(names, br.Name)
		}
		fmt.Fprintf(&b, "- Branches: %s\n", strings.Join(names, ", "))
	}
	if pc.Stale {
		b.WriteString("- ⚠ This brief is STALE: main moved past the sha it was written against.\n")
	}
	b.WriteString("\n## Brief\n\n")
	if pc.BriefMD != "" {
		b.WriteString(pc.BriefMD + "\n")
		if pc.BriefBy != "" {
			fmt.Fprintf(&b, "\n_Curated by %s_\n", pc.BriefBy)
		}
	} else {
		b.WriteString("No brief yet — a Lead can save one from the Korva console.\n")
	}
	return b.String()
}

// RenderDecisions produces decisions.md: the project's recent vault
// entries in compact form, ids resolvable via the vault_get MCP tool.
func RenderDecisions(d Data) string {
	var b strings.Builder
	b.WriteString(header(d, ""))
	fmt.Fprintf(&b, "# Recent team decisions — %s\n\n", d.Project)
	if len(d.Observations) == 0 {
		b.WriteString("No vault entries for this project yet.\n")
		return b.String()
	}
	b.WriteString("Full content of any entry: MCP tool `vault_get <id>`.\n\n")
	for _, o := range d.Observations {
		fmt.Fprintf(&b, "- `%s` **[%s]** %s\n", o.ID, o.Kind, o.Title)
		if s := firstLine(o.Content); s != "" {
			fmt.Fprintf(&b, "  %s\n", s)
		}
	}
	return b.String()
}

// firstLine collapses the text to a single ≤160-rune line.
func firstLine(s string) string {
	oneLine := strings.Join(strings.Fields(s), " ")
	r := []rune(oneLine)
	if len(r) > 160 {
		return strings.TrimRight(string(r[:160]), " ") + "…"
	}
	return oneLine
}

// Write materializes the three files under root/.korva/context/.
// Returns the relative paths written.
func Write(root string, d Data) ([]string, error) {
	dir := filepath.Join(root, filepath.FromSlash(Dir))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir %s: %w", dir, err)
	}
	files := []struct {
		name string
		body string
	}{
		{"portfolio.md", RenderPortfolio(d)},
		{"project-brief.md", RenderBrief(d)},
		{"decisions.md", RenderDecisions(d)},
	}
	out := make([]string, 0, len(files))
	for _, f := range files {
		rel := filepath.Join(filepath.FromSlash(Dir), f.name)
		if err := os.WriteFile(filepath.Join(root, rel), []byte(f.body), 0o644); err != nil {
			return out, fmt.Errorf("write %s: %w", rel, err)
		}
		out = append(out, rel)
	}
	return out, nil
}

// EnsureGitignore makes sure the project's .gitignore covers .korva/.
// Appends the line when missing (creating the file if needed); returns
// true when it changed the file.
func EnsureGitignore(root string) (bool, error) {
	path := filepath.Join(root, ".gitignore")
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read .gitignore: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == gitignoreLine || trimmed == ".korva" || trimmed == "/.korva/" || trimmed == "/.korva" {
			return false, nil
		}
	}
	var content string
	if len(data) == 0 {
		content = gitignoreLine + "\n"
	} else {
		content = strings.TrimRight(string(data), "\n") + "\n\n# Korva generated context (refreshed by `korva context pull`)\n" + gitignoreLine + "\n"
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write .gitignore: %w", err)
	}
	return true, nil
}
