package contextfiles

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/AlcanDev/korva-cli/internal/api"
)

func at(s string) *time.Time {
	t, _ := time.Parse(time.RFC3339, s)
	return &t
}

func sampleData() Data {
	return Data{
		ServerURL: "https://platform.korva.dev",
		Project:   "atlas",
		Context: &api.ProjectContext{
			Project:  "atlas",
			HeadSHA:  strings.Repeat("a", 40),
			Branch:   "main",
			RepoURL:  "https://example.com/org/atlas",
			PushedAt: at("2026-08-20T10:00:00Z"),
			BriefMD:  "Atlas is the billing service. Go + Postgres.",
			BriefBy:  "lead@team.com",
			Branches: []api.ContextBranch{{Name: "main"}, {Name: "develop"}},
			Stale:    true,
		},
		Portfolio: []api.ProjectContext{
			{Project: "atlas", HeadSHA: strings.Repeat("a", 40), Branch: "main",
				PushedAt: at("2026-08-20T10:00:00Z"), BriefMD: "Atlas is the billing service.", Stale: true},
			{Project: "lyra"}, // registry-only: never pushed
		},
		Observations: []api.Observation{
			{ID: "01OBS", Kind: "decision", Title: "Use slog",
				Content: "Chose slog over zerolog.\nStdlib alignment."},
		},
		GeneratedAt: time.Date(2026, 8, 22, 12, 0, 0, 0, time.UTC),
	}
}

func TestRenderBrief(t *testing.T) {
	out := RenderBrief(sampleData())
	for _, want := range []string{
		"generated by korva context pull",
		"main@aaaaaaaaaaaa",
		"# atlas",
		"STALE",
		"Atlas is the billing service.",
		"_Curated by lead@team.com_",
		"Branches: main, develop",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("brief missing %q:\n%s", want, out)
		}
	}
}

func TestRenderBriefNoContext(t *testing.T) {
	d := sampleData()
	d.Context = nil
	out := RenderBrief(d)
	if !strings.Contains(out, "no context record yet") || !strings.Contains(out, "korva context push") {
		t.Errorf("missing wiring hint:\n%s", out)
	}
}

func TestRenderPortfolio(t *testing.T) {
	out := RenderPortfolio(sampleData())
	for _, want := range []string{"## atlas", "## lyra", "never pushed (CI not wired)", "STALE"} {
		if !strings.Contains(out, want) {
			t.Errorf("portfolio missing %q:\n%s", want, out)
		}
	}
}

func TestRenderDecisions(t *testing.T) {
	out := RenderDecisions(sampleData())
	for _, want := range []string{"`01OBS`", "[decision]", "Use slog", "vault_get", "Chose slog over zerolog. Stdlib alignment."} {
		if !strings.Contains(out, want) {
			t.Errorf("decisions missing %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "\nStdlib") {
		t.Error("content snippet must be collapsed to one line")
	}
}

func TestWriteCreatesFiles(t *testing.T) {
	root := t.TempDir()
	written, err := Write(root, sampleData())
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	if len(written) != 3 {
		t.Fatalf("wrote %d files, want 3", len(written))
	}
	for _, rel := range written {
		if _, err := os.Stat(filepath.Join(root, rel)); err != nil {
			t.Errorf("missing %s: %v", rel, err)
		}
	}
}

func TestEnsureGitignore(t *testing.T) {
	root := t.TempDir()

	// No .gitignore yet → created with the line.
	changed, err := EnsureGitignore(root)
	if err != nil || !changed {
		t.Fatalf("first ensure: changed=%v err=%v", changed, err)
	}
	data, _ := os.ReadFile(filepath.Join(root, ".gitignore"))
	if !strings.Contains(string(data), ".korva/") {
		t.Fatalf(".gitignore missing entry: %q", data)
	}

	// Second call is a no-op.
	changed, err = EnsureGitignore(root)
	if err != nil || changed {
		t.Errorf("second ensure: changed=%v err=%v, want no-op", changed, err)
	}

	// Pre-existing content is preserved and appended to.
	root2 := t.TempDir()
	if err := os.WriteFile(filepath.Join(root2, ".gitignore"), []byte("node_modules/\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if changed, err = EnsureGitignore(root2); err != nil || !changed {
		t.Fatalf("append ensure: changed=%v err=%v", changed, err)
	}
	data, _ = os.ReadFile(filepath.Join(root2, ".gitignore"))
	if !strings.Contains(string(data), "node_modules/") || !strings.Contains(string(data), ".korva/") {
		t.Errorf("append lost content: %q", data)
	}
}
