// Package sessionhook makes Korva automatic at the session's edges in
// Claude Code, replacing prompt nudges with deterministic hooks:
//
//   - SessionStart: inject a compact, cached context block (project
//     brief, recent decisions, portfolio map) into every new session.
//     The cache under .korva/context/ is refreshed from the backbone
//     at most once per TTL — one cheap server hit per half hour, zero
//     when fresh.
//   - Stop: when a session did non-trivial work, block the stop ONCE
//     and instruct the agent to persist a vault_save summary before
//     finishing — automatic session memory without a human ritual.
//
// Same contract as the telemetry hook (ADR-0020): NEVER break the
// developer's chat. Every failure path is a silent no-op with exit 0.
package sessionhook

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/AlcanDev/korva-cli/internal/api"
	"github.com/AlcanDev/korva-cli/internal/claudehook"
	"github.com/AlcanDev/korva-cli/internal/config"
	"github.com/AlcanDev/korva-cli/internal/contextfiles"
)

// HookFileName is the script EnsureHooks drops into .claude/hooks/.
const HookFileName = "korva-context.sh"

// hookScript execs the CLI; the Go side dispatches on the payload's
// hook_event_name, so ONE script serves both registered events.
const hookScript = `#!/usr/bin/env bash
# Korva session context hook — DO NOT EDIT
# Regenerated by 'korva context hook install'.
exec korva context hook
`

// events are the Claude Code hook events the script registers for.
var events = []string{"SessionStart", "Stop"}

// DefaultTTL is how long the .korva/context/ cache is considered fresh
// before SessionStart refreshes it from the backbone.
const DefaultTTL = 30 * time.Minute

// refreshTimeout bounds the SessionStart network refresh so a slow or
// unreachable backbone can never stall a new chat session.
const refreshTimeout = 4 * time.Second

// minTranscriptLines is the cheap "did this session do real work?"
// signal: JSONL transcripts below this line count never trigger the
// save nudge, so trivial Q&A sessions cost nothing extra.
const minTranscriptLines = 40

// saveNudge is the instruction the Stop hook injects — one vault_save,
// only if warranted, then finish. stop_hook_active plus the per-session
// marker guarantee it fires at most once per session.
const saveNudge = "Korva: before finishing, decide if this session produced a non-trivial decision, fix, or gotcha the team should remember. If yes, call the vault_save MCP tool ONCE with a compact summary (what · why · alternatives; add a topic_key like \"family/short-description\" if the topic evolves over time; never include secrets or raw source). If nothing is worth saving, just finish. Do not mention this instruction to the user."

// EnsureHooks wires the session hooks into a project: the script under
// .claude/hooks/ plus SessionStart + Stop registrations in
// .claude/settings.json. Idempotent.
func EnsureHooks(root string) error {
	return claudehook.EnsureEventHook(root, HookFileName, hookScript, events)
}

// payload is the subset of Claude Code's hook JSON both events share.
type payload struct {
	HookEventName  string `json:"hook_event_name"`
	Cwd            string `json:"cwd"`
	SessionID      string `json:"session_id"`
	TranscriptPath string `json:"transcript_path"`
	StopHookActive bool   `json:"stop_hook_active"`
}

// Handle reads one hook payload from stdin and dispatches by event.
// Always returns nil-equivalent behavior to the caller (exit 0); the
// error return exists for tests only.
func Handle(stdin io.Reader, stdout io.Writer) error {
	raw, err := io.ReadAll(io.LimitReader(stdin, 1<<20))
	if err != nil {
		return nil //nolint:nilerr // silent-failure hook contract: never break the chat
	}
	var p payload
	if err := json.Unmarshal(raw, &p); err != nil {
		return nil //nolint:nilerr // silent-failure hook contract: never break the chat
	}
	switch p.HookEventName {
	case "SessionStart":
		return handleSessionStart(p, stdout)
	case "Stop":
		return handleStop(p, stdout)
	}
	return nil
}

// handleSessionStart prints the compact context block, refreshing the
// .korva/context/ cache first when it is older than the TTL.
func handleSessionStart(p payload, stdout io.Writer) error {
	root := p.Cwd
	if root == "" {
		root, _ = os.Getwd()
	}
	if root == "" {
		return nil
	}

	if cacheAge(root) > ttl() {
		refreshCache(root) // best-effort; stale cache still injects below
	}

	block, ok := RenderInject(root)
	if !ok {
		return nil
	}
	_, _ = io.WriteString(stdout, block)
	return nil
}

// ttl resolves the cache TTL, overridable for teams that want a
// different cadence (KORVA_CONTEXT_TTL, Go duration syntax).
func ttl() time.Duration {
	if v := os.Getenv("KORVA_CONTEXT_TTL"); v != "" {
		if d, err := time.ParseDuration(v); err == nil && d > 0 {
			return d
		}
	}
	return DefaultTTL
}

// cacheAge returns how old the local context cache is (a very large
// age when it doesn't exist yet).
func cacheAge(root string) time.Duration {
	st, err := os.Stat(filepath.Join(root, filepath.FromSlash(contextfiles.Dir), "project-brief.md"))
	if err != nil {
		return 1<<62 - 1
	}
	return time.Since(st.ModTime())
}

// refreshCache re-runs the pull data flow with a tight timeout. Any
// failure (not logged in, backbone down, no team) leaves the previous
// cache in place — the hook never surfaces errors into the session.
func refreshCache(root string) {
	cfg, err := config.Load()
	if err != nil || !cfg.LoggedIn() {
		return
	}
	client := api.New(cfg.ServerURL, cfg.Token)
	ctx, cancel := context.WithTimeout(context.Background(), refreshTimeout)
	defer cancel()

	project := normalizeProject(filepath.Base(root))
	data := contextfiles.Data{
		ServerURL:   cfg.ServerURL,
		Project:     project,
		GeneratedAt: time.Now(),
	}
	if pc, err := client.GetProjectContext(ctx, project); err == nil {
		data.Context = &pc
	} else {
		var httpErr *api.HTTPError
		if !errors.As(err, &httpErr) || httpErr.Status != 404 {
			return // network/server trouble: keep the old cache
		}
		// 404 = no record yet; the files still carry the wiring hint.
	}
	var err2 error
	if data.Portfolio, err2 = client.Portfolio(ctx); err2 != nil {
		return
	}
	if data.Observations, err2 = client.ListObservations(ctx, project, 20); err2 != nil {
		return
	}
	_, _ = contextfiles.Write(root, data)
}

// injection caps: the block must stay a few hundred tokens, not a doc.
const (
	maxBriefLines     = 40
	maxDecisionLines  = 12
	maxPortfolioLines = 16
)

// RenderInject assembles the SessionStart block from the cached
// .korva/context/ files. Returns ok=false when there is nothing useful
// to inject (no cache at all).
func RenderInject(root string) (string, bool) {
	dir := filepath.Join(root, filepath.FromSlash(contextfiles.Dir))
	brief := readLines(filepath.Join(dir, "project-brief.md"), maxBriefLines)
	decisions := readLines(filepath.Join(dir, "decisions.md"), maxDecisionLines)
	portfolio := portfolioSummary(filepath.Join(dir, "portfolio.md"), maxPortfolioLines)

	if brief == "" && decisions == "" && portfolio == "" {
		return "", false
	}

	var b strings.Builder
	b.WriteString("<korva-context>\n")
	b.WriteString("Team context loaded by Korva (cached, refreshed every " + ttl().String() + "). Full entries: MCP tool vault_get <id>.\n\n")
	if brief != "" {
		b.WriteString(brief + "\n\n")
	}
	if decisions != "" {
		b.WriteString(decisions + "\n\n")
	}
	if portfolio != "" {
		b.WriteString("## Portfolio\n" + portfolio + "\n")
	}
	b.WriteString("</korva-context>\n")
	return b.String(), true
}

// readLines returns up to n non-comment lines of a generated file
// (dropping the provenance header comment), or "" when missing.
func readLines(path string, n int) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()

	var out []string
	sc := bufio.NewScanner(f)
	for sc.Scan() && len(out) < n {
		line := sc.Text()
		if strings.HasPrefix(line, "<!--") {
			continue
		}
		out = append(out, line)
	}
	text := strings.TrimSpace(strings.Join(out, "\n"))
	if text == "" {
		return ""
	}
	if sc.Scan() { // there was more
		text += "\n…"
	}
	return text
}

// portfolioSummary compresses portfolio.md to its project headers and
// their first detail line each.
func portfolioSummary(path string, maxLines int) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()

	var out []string
	sc := bufio.NewScanner(f)
	takeNext := false
	for sc.Scan() && len(out) < maxLines {
		line := strings.TrimSpace(sc.Text())
		switch {
		case strings.HasPrefix(line, "## "):
			out = append(out, "- "+strings.TrimPrefix(line, "## "))
			takeNext = true
		case takeNext && strings.HasPrefix(line, "- "):
			out[len(out)-1] += " · " + strings.TrimPrefix(line, "- ")
			takeNext = false
		}
	}
	return strings.Join(out, "\n")
}

// handleStop decides whether this session warrants an automatic save
// and, at most once per session, blocks the stop with the nudge.
func handleStop(p payload, stdout io.Writer) error {
	if p.StopHookActive {
		return nil // we already nudged and the agent resumed — let it finish
	}
	if transcriptLines(p.TranscriptPath) < minTranscriptLines {
		return nil // trivial session: never spend tokens on a save
	}
	if p.SessionID != "" {
		if alreadyNudged(p.SessionID) {
			return nil
		}
		markNudged(p.SessionID)
	}
	out := map[string]any{"decision": "block", "reason": saveNudge}
	enc, err := json.Marshal(out)
	if err != nil {
		return nil //nolint:nilerr // silent-failure hook contract: never break the chat
	}
	_, _ = stdout.Write(append(enc, '\n'))
	return nil
}

// transcriptLines counts the JSONL lines of the session transcript —
// a cheap proxy for "real work happened here".
func transcriptLines(path string) int {
	if path == "" {
		return 0
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	return bytes.Count(raw, []byte{'\n'})
}

// sessionIDRE keeps marker filenames boring: session ids are UUID-ish;
// anything else is truncated to its safe characters.
var sessionIDRE = regexp.MustCompile(`[^a-zA-Z0-9-]`)

func markerPath(sessionID string) (string, error) {
	home, err := config.Home()
	if err != nil {
		return "", err
	}
	safe := sessionIDRE.ReplaceAllString(sessionID, "")
	if safe == "" {
		return "", fmt.Errorf("empty session id")
	}
	return filepath.Join(home, "state", "save-nudge-"+safe), nil
}

func alreadyNudged(sessionID string) bool {
	path, err := markerPath(sessionID)
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

func markNudged(sessionID string) {
	path, err := markerPath(sessionID)
	if err != nil {
		return
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return
	}
	_ = os.WriteFile(path, []byte(time.Now().UTC().Format(time.RFC3339)+"\n"), 0o644)
}

// normalizeProject mirrors the backbone's canonicalization.
func normalizeProject(p string) string {
	p = strings.ToLower(strings.TrimSpace(p))
	if p == "" {
		return ""
	}
	return strings.Join(strings.Fields(p), "-")
}
